name: 删除workflow，删除releases
on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 16 * * *
    
jobs:
  del_runs:
    runs-on: ubuntu-20.04
    steps:
    
    - name: 删除workflow，清理工作流，保留最近的5天记录
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 5
        keep_minimum_runs: 0
    
    - name: 删除releases，清理旧版本，保留1个版本
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 1
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
